### ISSUE TITLE
Wrong password converted for AD

### ISSUE THREAD

**Issue by kadogo** [lsc-project/lsc#186] opened 2022-05-06 10:20 UTC
Hello

I notice that the password "1aDhgtryjhddç" doesn't work in AD when synchronized with LSC.

lsc.xml

```
# grep 'getUnicode' lsc.xml 
            <string>AD.getUnicodePwd("1aDhgtryjhddç")</string>
```

lsc.ldif

```
# grep unicode lsc.ldif 
replace: unicodePwd
unicodePwd:: IgAxAGEARABoAGcAdAByAHkAagBoAGQAZADvv70AIgA=
```

When I convert the password manually with bash it is working like expected

```
# printf '"%s"' "1aDhgtryjhddç" | iconv --to utf-16le | base64
IgAxAGEARABoAGcAdAByAHkAagBoAGQAZADnACIA
```

We notice clearly that the results are not the same between LSC and my bash command

Cheers

**Comment by artlog** [comment] 2022-09-23 13:16
taking a look...

**Comment by artlog** [comment] 2022-09-23 14:10
@kadogo can you provide first lines of lsc.xml , to check for <?xml  encoding = line .
If content of lsc.xml is not encoded according to encoding such issue might happen.
input char won't be recognized and will be translated as invalid '�' utf16-le : efbf bd00  by java library.

**Comment by kadogo** [comment] 2022-09-23 14:29
Hello @artlog 

I don't have any line that mention the encoding in my lsc.xml files.

```
<?xml version="1.0" ?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0"> 
...
```

Cheers

**Comment by artlog** [comment] 2022-09-23 14:36
@kadogo 
Do you know what encoding was used for this file ? 
You could  try  changing first line to  <?xml version="1.0" encoding= "UTF-8" ?>  or   <?xml version="1.0" encoding= ISO-8859-1" ?>

**Comment by kadogo** [comment] 2022-09-27 14:23
Hello @artlog 

```
# file /etc/lsc/lsc.xml 
/etc/lsc/lsc.xml: XML 1.0 document, ASCII text
```

I tried with the 2 lines (UTF-8 and ISO-8859-1) and no succes.

Cheers

**Comment by artlog** [comment] 2022-09-27 15:03
It is because is it not unicode :

creating a dummy xml file test.xml
```
<?xml version="1.0" ?>
<lsc xmlns="http://lsc-project.org/XSD/lsc-core-2.1.xsd" revision="0"> 
  <string>AD.getUnicodePwd("1aDhgtryjhddç")</string>
</lsc>
```

```
$ file test.xml
test.xml: XML 1.0 document, Unicode text, UTF-8 text
```
```
$ cat test.xml  | iconv -f 'utf8' -t 'ISO-8859-1' > testascii.xml 
$ file testascii.xml 
testascii.xml: XML 1.0 document, ISO-8859 text
```

There is something unusual with your lsc xml source, but default xml should be utf-8.

**Comment by artlog** [comment] 2022-09-28 04:38
@kadogo what operating system and java version do you have ?

One remark : <?xml version="1.0" encoding= "UTF-8" ?> is just an indication for xml parser, actual content should be encoded in utf8 by your editor.

**Comment by artlog** [comment] 2022-09-28 06:16
@kadogo thanks for not giving up, i have to create a test for this, looking again a code there is something weird with code 'new String(quotedPassword.getBytes("UTF-16LE"))' .

**Comment by artlog** [comment] 2022-09-28 08:52
quotedPassword.getBytes("UTF-16LE") is correct but conversion to String with String(quotedPassword.getBytes("UTF-16LE")) is not.

For two reasons, major one is that java String does not keep encoding, it has an internal representation.
It is a hack to be able to control String  encoding with api. Then it relies on default system encoding, that basically can be UTF8 or some older iso 256  characters wide like ISO-8859-1.

If system is UTF8 then any non US-ASCII will be smashed out, so our 'ç' here, if system is ISO-8859 String encoding will somehow be preserved but this will affect all Strings and might loose UTF8 encoding on any other ldap attribute.

This UTF16-LE encoding is very specific to unicodePW as described here https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2

There is some java code reference for this here https://ldapwiki.com/wiki/Example%20-%20Active%20Directory%20Change%20Password%20JNDI

But this sample does handle byte[] array directly to build ldap attribute, lsc uses String.  

A correct fix for this would be a dedicated handling of unicodePw AD attribute within lsc and no requirement to handle attribute encoding through call AD.getUnicodePwd within scripts.

forcing default system to not be utf8 will allow password to be generated correctly, but will impact other ldap attributes.

this can be confirmed this way 

LANG="fr_FR" /usr/bin/lsc

vs

LANG="fr_FR.UTF-8" /usr/bin/lsc

**Comment by artlog** [comment] 2022-09-28 09:06
@kadogo with UTF-8 lang any special character outside us-ascii won't be encoded correctly since java replace character by the famous �. In my test it should work with LANG=en_US .

**Comment by coudot** [comment] 2024-02-09 17:30
I confirm that I can reproduce the bug

**Comment by coudot** [comment] 2024-02-12 08:48
After a lot of test, here is a working solution:
* return unicode password as `bytes[]` and use this value in unicodePwd dataset
* Set unicodePwd as binary attribute in the LDAP connection

**Closed** 2024-02-15 07:48 UTC
Labels: bug
